FROM alpine:latest as certs
RUN apk --update add ca-certificates

FROM scratch

COPY --from=certs /etc/ssl/certs/ca-certificates.crt

VOLUME /srv
EXPOSE 80

COPY filebrowser.json /.filebrowser.json
COPY filebrowser.linux_armv7 /filebrowser

ENTRYPOINT [ "/filebrowser" ]
