#!/bin/bash
curl -s https://api.github.com/repos/filebrowser/filebrowser/releases/latest \
  | grep browser_download_url \
  | grep linux-amd64 \
  | cut -d '"' -f 4 \
  | xargs curl -L \
  | tar -zx \
  && mv filebrowser filebrowser.linux_amd64
  curl -s https://api.github.com/repos/filebrowser/filebrowser/releases/latest \
  | grep browser_download_url \
  | grep linux-armv7 \
  | cut -d '"' -f 4 \
  | xargs curl -L \
  | tar -zx \
  && mv filebrowser filebrowser.linux_armv7
